name: link-check

on: [pull_request]

jobs:
  base:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Link check
        uses: peter-evans/link-checker@v1
        with:
          args: -r -x /media/.* -v *
